# Generated by Django 5.2.3 on 2025-07-08 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_address'),
        ('Store', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.address'),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
