# Generated by Django 5.2.3 on 2025-07-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_orders_address_orders_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.CharField(choices=[('250gm', '250 GM'), ('500gm', '5000 GM'), ('1kg', '1 KGM'), ('2kg', '2 KGM')], default='1kg', max_length=100),
        ),
    ]
