# Generated by Django 5.2.3 on 2025-07-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_products_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.CharField(choices=[('250gm', '250 GM'), ('500gm', '5000 GM'), ('1kg', '1 KGM'), ('1500gm', '1500 GM'), ('2kg', '2 KGM')], default='1kg', max_length=100),
        ),
    ]
