# Generated by Django 5.2.3 on 2025-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_orders_weight_alter_products_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
