# Generated by Django 5.2.3 on 2025-07-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_orders_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
