# Generated by Django 5.2.3 on 2025-07-13 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_alter_orders_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 13, 12, 19, 33, 736226, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
