# Generated by Django 5.2.3 on 2025-07-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_alter_orders_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.CharField(blank=True, null=True),
        ),
    ]
