# Generated by Django 5.2.3 on 2025-12-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.CharField(choices=[('250gm', '250 GM'), ('500gm', '500 GM'), ('1kg', '1 KGM'), ('1500gm', '1500 GM'), ('2kg', '2 KGM')], default='1kg', max_length=100),
        ),
    ]
