# Generated by Django 5.2.3 on 2025-12-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_alter_products_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('confirm', 'Confirmed'), ('cancel', 'Cancelled')], default='draft', max_length=20, null=True),
        ),
    ]
