# Generated by Django 5.2.3 on 2026-07-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0021_alter_orders_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
    ]
