# Generated by Django 5.2.3 on 2025-07-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bakery',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
