# Generated by Django 5.2.3 on 2025-07-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_bakery_instagram_bakery_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowCaseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/showcase_images')),
            ],
        ),
    ]
