# Generated by Django 5.2.3 on 2025-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_unitofmeasurements_showcaseimages_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseimages',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
