# Generated by Django 5.2.3 on 2025-07-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_showcaseimages_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='address',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bakery',
            name='phone',
            field=models.URLField(blank=True, null=True),
        ),
    ]
