# Generated by Django 5.2.3 on 2025-07-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_bakery_address_bakery_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
