# Generated by Django 5.2.3 on 2025-07-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_bakery_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakery',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
