# Generated by Django 5.2.3 on 2025-07-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_bakery_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakery',
            name='user',
        ),
    ]
