# Generated by Django 5.2.3 on 2025-07-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowCaseImages',
        ),
    ]
