# Generated by Django 5.2.3 on 2025-07-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_delete_showcaseimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='currency',
            field=models.CharField(blank=True, default='INR', null=True),
        ),
    ]
