# Generated by Django 5.2.3 on 2025-07-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_bakery_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
