# Generated by Django 5.2.3 on 2025-07-12 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_countries_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.countries'),
        ),
    ]
