# Generated by Django 5.2.3 on 2026-07-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_alter_userinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='logo',
            field=models.ImageField(upload_to='images/logo/'),
        ),
    ]
