# Generated by Django 5.2.3 on 2025-07-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0002_remove_order_customer_remove_order_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
