# Generated by Django 5.2.3 on 2025-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0003_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=10, null=True),
        ),
    ]
