# Generated by Django 5.2.3 on 2025-07-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsale', '0004_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
    ]
